TensorFlow Basics
-------------------

In [1]:
import tensorflow as tf
import numpy as np

First we define our session

In [2]:
sess = tf.Session()

In [3]:
a = 1
b = 3

Whenever we create a TensorFlow object we are creating a node in our graph's Session.

In [4]:
add = tf.add(a,b)

In [5]:
add

<tf.Tensor 'Add:0' shape=() dtype=int32>

We consider calculating processes as running nodes in our graph.  

In [6]:
print(a,'+',b, '=')
sess.run(add)

1 + 3 =


4

But what if we change one of the variables?

In [7]:
b = 1

What do you think our add function will output?

In [8]:
print(a,'+',b, '=')
sess.run(add)

1 + 1 =


4

Of course it will output the same answer because we have not updated the node in our graph.

In [9]:
print(a,'+',b, '=')
add = tf.add(a,b)
sess.run(add)

1 + 1 =


2

But changing our node everytime we want to change our values is eneffecient, instead we use placeholders.  Then when running the node we can feed in any value we wish.

In [10]:
A = tf.placeholder(tf.float32, shape=(1))
B = tf.placeholder(tf.float32, shape=(1))

In [11]:
add = tf.add(A,B)

In [12]:
sess.run(add, feed_dict={A:[1], B:[2]})

array([ 3.], dtype=float32)

In [13]:
sess.run(add, feed_dict={A:[7], B:[7]})

array([ 14.], dtype=float32)

But what if we wanted to add a bunch of numbers at once?  We create the shape to be None so that we can feed in any amount we would like.

In [14]:
C = tf.placeholder(tf.float32, shape=(None,1))
D = tf.placeholder(tf.float32, shape=(None,1))

In [15]:
add = tf.add(C,D)

For feeding tensors of various sizes using numpy arrays is certainly the easiest method.

In [16]:
a = np.random.uniform(-10, 10, size=(5,1))
b = np.random.uniform(-10, 10, size=(5,1))

In [17]:
a

array([[-0.9263946 ],
       [ 3.55183282],
       [-2.58804782],
       [ 0.77374574],
       [ 7.35993647]])

In [18]:
b

array([[ 8.0966635 ],
       [ 6.23255083],
       [-4.84058277],
       [ 4.13536855],
       [ 7.72558494]])

In [19]:
sess.run(add, feed_dict={C:a, D:b})

array([[  7.17026901],
       [  9.78438377],
       [ -7.42863083],
       [  4.90911388],
       [ 15.0855217 ]], dtype=float32)

We can also create a new node with it's input being an existing node.

In [20]:
squared = tf.square(add)
divided = tf.divide(squared,10)

In [21]:
sess.run(divided, feed_dict={C:a, D:b})

array([[  5.14127588],
       [  9.57341671],
       [  5.51845551],
       [  2.40994   ],
       [ 22.75729752]], dtype=float32)

We can choose to run whichever node we would like

In [22]:
sess.run(squared, feed_dict={C:a, D:b})

array([[  51.41275787],
       [  95.73416901],
       [  55.18455505],
       [  24.09939957],
       [ 227.57296753]], dtype=float32)

In [23]:
graph = tf.get_default_graph()

In [26]:
graph.get_operations()

[<tf.Operation 'Add/x' type=Const>,
 <tf.Operation 'Add/y' type=Const>,
 <tf.Operation 'Add' type=Add>,
 <tf.Operation 'Add_1/x' type=Const>,
 <tf.Operation 'Add_1/y' type=Const>,
 <tf.Operation 'Add_1' type=Add>,
 <tf.Operation 'Placeholder' type=Placeholder>,
 <tf.Operation 'Placeholder_1' type=Placeholder>,
 <tf.Operation 'Add_2' type=Add>,
 <tf.Operation 'Placeholder_2' type=Placeholder>,
 <tf.Operation 'Placeholder_3' type=Placeholder>,
 <tf.Operation 'Add_3' type=Add>,
 <tf.Operation 'Square' type=Square>,
 <tf.Operation 'truediv/y' type=Const>,
 <tf.Operation 'truediv' type=RealDiv>]